pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'javac -d target main/HelloWorld.java'
        sh 'java -cp target HelloWorld.MainClass'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        sh '''
                sudo apt update
                sudo apt install -y nodejs npm
                '''
        sh 'npm -v'
      }
    }
  }
}
