pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Ensure Maven is available
        sh 'mvn --version'

        // Create necessary directories under target
        sh 'mkdir -p target/multi/stage/multi/agent'

        // Compile the Java program
        sh 'javac -d target multi-stage-multi-agent/HelloWorld.java'

        // List the contents of the target directory for debugging
        sh 'ls -R target'

        // Run the Java program
        sh 'java -cp target multi.stage.multi.agent.HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'  // Verify Node.js version
        sh 'npm -v'  // Verify npm version
      }
    }
  }
}
