pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'  // Ensure Maven is available, though not needed for the build
        sh 'javac -d target multi-stage-multi-agent/HelloWorld.java'  // Manually compile the Java program
        sh 'java -cp target multi.stage.multi.agent.HelloWorld'  // Run the Java program
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'  // Verify Node.js version
        sh 'npm -v'  // Verify npm version
      }
    }
  }
}
